# **Problem 2:**

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

In [0]:
import numpy as np
import sys

Sources used: 

https://towardsdatascience.com/convolutional-neural-network-17fb77e76c05

https://towardsdatascience.com/beginners-guide-to-understanding-convolutional-neural-networks-ae9ed58bb17d


In [0]:
# @param: input_matrix, an (n x n) matrix
# @param: s, the size of our (m x m) max pooling layer
# @return: Output_mat, an (s x s) matrix
def maxpooling2d(input_mat, s):
  if input_mat.shape[0] != input_mat.shape[1]:
    raise Exception("Input_mat needs to be a square matrix.")
  if (s > input_mat.shape[0]):
    raise Exception("Given s was larger than our input matrix size.")

  input_size = input_mat.shape[0]
  output_size = int((input_size - s) / s + 1)

  output_mat = np.zeros((output_size, output_size))

  for i in np.arange(output_size):
    for j in np.arange(output_size):

      output_mat[i][j] = -sys.maxsize
      for m in np.arange(s):
        for n in np.arange(s):
          output_mat[i][j] = max(output_mat[i][j], input_mat[m+i*s][n+j*s])

  return output_mat

## **Test Cases**

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!


Exception: ignored