# **Problem 1**

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

In [0]:
import numpy as np
import sys

For information on convolutions, specifically flipping, the following two sources were used:

https://cs.stackexchange.com/questions/11591/2d-convolution-flipping-the-kernel

https://towardsdatascience.com/convolution-vs-correlation-af868b6b4fb5

In [0]:
# @param: input_mat (n x n) matrix
# @param: kernel_mat (m x m) matrix
# @returns: A (k x k) matrix made by performing a convolution on input_mat with kernel_mat
def conv2d(input_mat, kernel_mat):
  input_size = input_mat.shape[0]
  kernel_size = kernel_mat.shape[0]

  # To do a convolution, Our kernel_mat cannot be larger than input_mat
  if kernel_size > input_size: 
    raise Exception(f"Our kernel is larger than our input matrix. We cannot perform a convolution.")
  
  # We should be given a square input and kernel mat
  if input_mat.shape[0] != input_mat.shape[1]:
    raise Exception(f"Input mat should be a square matrix")
  if kernel_mat.shape[0] != kernel_mat.shape[1]:
    raise Exception(f"Kernel mat should be a square matrix")

  # This will be the dimensions of our new matrix after convolutions were made
  output_size = input_size - kernel_size + 1
  output_mat = np.zeros((output_size, output_size))

  # Flip kernel
  kernel_mat = np.flipud(kernel_mat)
  kernel_mat = np.fliplr(kernel_mat)

  # Perform convolution
  for i in np.arange(output_size):
    for j in np.arange(output_size):
      summ = 0

      for m in np.arange(kernel_size):
        for n in np.arange(kernel_size):
          summ += input_mat[i+m][j+n] * kernel_mat[m][n]
      
      output_mat[i][j] = summ

  return output_mat

## **Test Cases**

In [0]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  # if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #   output_mat = []
  # else:
  #   output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!



Exception: ignored