# Homework 1: Problem 2

Outputs the product of a list of numpy arrays. If we cannot take the product of two matrices, prints out their dimensions. 


In [0]:
import numpy as np

Matrix multiplication between two matrices, A and B, is only possible if A is a (M x N) dimensional matrix and B is a (N x K) dimensional matrix, where M, N, and K are any positive number.

Example:  
Let A =  
$[1, 2, 3]$    
$[4, 5, 6]$  
$[7, 8, 9]$

Let B =   
$[4]$  
$[1]$

A*B would not be possible since A is a (3 x 3) matrix and B is a (2 x 1) Matrix. 

Example:  
Let A =  
$[1, 2, 3]$    
$[4, 5, 6]$  
$[7, 8, 9]$

Let B =   
$[1, 2]$    
$[4, 1]$  
$[7, 8]$

A * B is possible since A is a (3 x 3) matrix and B is a (3 x 2) matrix


Also, note that matrix multiplication is not commutative since it relies on matrix dimensions. Thus, A * B is not the same as B * A


In [0]:
def multiply_matrices(matrices):
  if matrices is None or len(matrices) == 0:
    try:
      raise Exception("No matrices were passed. Need at least two to multiply")
    except Exception as e:
      print(e)
  elif len(matrices) == 1:
    try:
      raise Exception("Only one matrix was passed. Need at least two to multiply")
    except Exception as e:
      print(e)
  else:
    for i in range(len(matrices)):

      # Get the first matrix, A
      current_matrix = matrices[i]
      
      # Start from 0 since A * B is not the same as B * A, so we could have different things
      for j in range(len(matrices)):
        if i != j:
          try:
            print(f"{current_matrix} * {matrices[j]} = ")
            current_matrix = np.matmul(current_matrix, matrices[j])
            print(current_matrix)
            
          except:
            print(f"Cannot multiply matrices with dimensions {current_matrix.shape} and {matrices[j].shape}")
# multiply_matrices([np.eye(3),np.ones(3)])
# multiply_matrices([]) 

#TA comment

**Your code doesn't work when your list is empty or a single matrix.**

**You're checking for every pair of matrices in the list if their dimension allows them to be multiplied, you should fix this. e.g. for list $[A_1, A_2, A_3]$ it should output the matrix $A_1\times A_2\times  A_3$ if possible.**


In [0]:
multiply_matrices([])

In [0]:
multiply_matrices([np.ones(2)])

In [0]:
multiply_matrices([np.eye(3),np.ones(3)]) # printing twice?
# While it prints twice, it's not the same ordering being done

[1. 1. 1.]
[1. 1. 1.]


In [0]:
multiply_matrices([np.eye(3),np.eye(3),np.ones(2)])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Cannot multiply matrices with dimensions (3, 3) and (2,)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Cannot multiply matrices with dimensions (3, 3) and (2,)
Cannot multiply matrices with dimensions (2,) and (3, 3)
Cannot multiply matrices with dimensions (2,) and (3, 3)
