# Analyzing MNIST dataset 


## Loading the MNIST digits data set, importing packages

In [0]:
import matplotlib.pyplot as plt
import numpy as np
import time 
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

## Compute average MNIST digits

In [0]:
lbl_avg = [0]*10
img_avg = np.array([np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28)), np.ones((28, 28))])
for i in range(len(train_labels)):
  lbl_avg[train_labels[i] - 1] += 1
  img_avg[train_labels[i] - 1] += train_images[i]


# Calculate the avera
for i in range(10):
  img_avg[i] /= lbl_avg[i]
print(img_avg)

# Calculate the average for each label
lbl_avg = [x/10 for x in lbl_avg]
print(lbl_avg)

(28, 28)
[[[0.00014832 0.00014832 0.00014832 ... 0.00014832 0.00014832 0.00014832]
  [0.00014832 0.00014832 0.00014832 ... 0.00014832 0.00014832 0.00014832]
  [0.00014832 0.00014832 0.00014832 ... 0.00014832 0.00014832 0.00014832]
  ...
  [0.00014832 0.00014832 0.00014832 ... 0.00014832 0.00014832 0.00014832]
  [0.00014832 0.00014832 0.00014832 ... 0.00014832 0.00014832 0.00014832]
  [0.00014832 0.00014832 0.00014832 ... 0.00014832 0.00014832 0.00014832]]

 [[0.00016784 0.00016784 0.00016784 ... 0.00016784 0.00016784 0.00016784]
  [0.00016784 0.00016784 0.00016784 ... 0.00016784 0.00016784 0.00016784]
  [0.00016784 0.00016784 0.00016784 ... 0.0278617  0.00016784 0.00016784]
  ...
  [0.00016784 0.00016784 0.00016784 ... 0.01477006 0.01762336 0.00016784]
  [0.00016784 0.00016784 0.00016784 ... 0.00016784 0.00016784 0.00016784]
  [0.00016784 0.00016784 0.00016784 ... 0.00016784 0.00016784 0.00016784]]

 [[0.00016311 0.00016311 0.00016311 ... 0.00016311 0.00016311 0.00016311]
  [0.00016311